"""
ChatSession.slug is generated by save() (audit P2.1 root cause).

save() used to skip slug generation on purpose, so a session created through
POST /api/v1/chat/sessions/ had slug=None until its first message, and the rest of the
code defended itself with hasattr/try/except ("migration may not have run").
"""
import importlib

import pytest
from django.apps import apps as global_apps
from django.contrib.auth.models import User

from src.apps.legislation.models import ChatSession

pytestmark = pytest.mark.django_db

migration = importlib.import_module("src.apps.legislation.migrations.0012_backfill_chatsession_slug")


@pytest.fixture
def user():
    return User.objects.create_user("ana", password="x")


def test_new_session_gets_a_12_char_slug_automatically(user):
    s = ChatSession.objects.create(user=user, title="t")
    assert len(s.slug) == 12 and s.slug.isalnum() and s.slug == s.slug.lower()


def test_explicit_slug_is_preserved(user):
    assert ChatSession.objects.create(user=user, title="t", slug="meu-slug").slug == "meu-slug"


def test_slugs_are_unique_across_many_sessions(user):
    slugs = {ChatSession.objects.create(user=user, title=str(i)).slug for i in range(60)}
    assert len(slugs) == 60


def test_generation_retries_on_collision(user, monkeypatch):
    ChatSession.objects.create(user=user, title="a", slug="aaaaaaaaaaaa")
    seq = iter(["a" * 12, "a" * 12, "b" * 12])
    monkeypatch.setattr(
        "secrets.choice", lambda alphabet, _it=iter(list("".join(seq))): next(_it)
    )
    assert ChatSession(user=user, title="t").generate_slug() == "b" * 12


def test_slug_is_persisted_even_with_update_fields(user):
    s = ChatSession(user=user, title="t")
    s.save(update_fields=None)
    fresh = ChatSession(user=user, title="u")
    fresh.save()
    fresh.slug = None
    fresh.save(update_fields=["title"])          # regenerates AND must persist the slug
    assert ChatSession.objects.get(pk=fresh.pk).slug


def test_backfill_gives_legacy_sessions_a_unique_slug_and_keeps_existing_ones(user):
    keep = ChatSession.objects.create(user=user, title="keep", slug="keepme000000")
    legacy = [ChatSession.objects.create(user=user, title=f"l{i}") for i in range(3)]
    ChatSession.objects.filter(pk__in=[s.pk for s in legacy]).update(slug=None)
    ChatSession.objects.filter(pk=legacy[0].pk).update(slug="")

    migration.backfill_slugs(global_apps, None)

    got = [ChatSession.objects.get(pk=s.pk).slug for s in legacy]
    assert all(got) and len(set(got)) == 3
    assert ChatSession.objects.get(pk=keep.pk).slug == "keepme000000"


def test_backfill_does_not_touch_updated_at(user):
    s = ChatSession.objects.create(user=user, title="t")
    ChatSession.objects.filter(pk=s.pk).update(slug=None)
    before = ChatSession.objects.get(pk=s.pk).updated_at
    migration.backfill_slugs(global_apps, None)
    assert ChatSession.objects.get(pk=s.pk).updated_at == before


def test_migration_is_reversible():
    assert migration.Migration.operations[0].reverse_code is not None
