# Generated by Django 5.0.9 on 2026-09-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentRecord',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('session_hash', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('size', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=150)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('text_storage_key', models.CharField(max_length=500, unique=True)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='saplsyncstate',
            new_name='operations__source_357f4b_idx',
            old_name='operations_source_last_success',
        ),
        migrations.RenameIndex(
            model_name='saplsyncstate',
            new_name='operations__lease_u_3cbca1_idx',
            old_name='operations_lease_until',
        ),
        migrations.AddIndex(
            model_name='attachmentrecord',
            index=models.Index(fields=['session_hash', 'created_at'], name='operations__session_b55e34_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentrecord',
            index=models.Index(fields=['expires_at'], name='operations__expires_3ac437_idx'),
        ),
    ]
