# Generated by Django 5.2.17 on 2026-10-03 04:21

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_corpus_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveImportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archive_sha256', models.CharField(db_index=True, max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Informe um SHA-256 hexadecimal válido.')])),
                ('manifest_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Informe um SHA-256 hexadecimal válido.')])),
                ('manifest_path', models.CharField(help_text='Path operacional privado; nunca é serializado em API pública.', max_length=1000)),
                ('cursor', models.PositiveIntegerField(default=0)),
                ('total_entries', models.PositiveIntegerField(default=0)),
                ('import_limit', models.PositiveIntegerField(default=40)),
                ('batch_size', models.PositiveIntegerField(default=10)),
                ('stats_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('planned', 'Planejada'), ('running', 'Em execução'), ('paused', 'Pausada'), ('completed', 'Concluída'), ('failed', 'Falha')], default='planned', max_length=16)),
                ('lease_token', models.CharField(blank=True, max_length=64)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['archive_sha256', 'status'], name='archive_run_hash_status_idx'), models.Index(fields=['status', 'lease_until'], name='archive_run_lease_idx')],
            },
        ),
    ]
