# Generated by Django 5.2.17 on 2026-10-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_archiveimportrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormativeWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedupe_key', models.CharField(max_length=180, unique=True)),
                ('source_kind', models.CharField(default='norma', max_length=32)),
                ('source_id', models.CharField(max_length=100)),
                ('source_revision', models.CharField(max_length=64)),
                ('stage', models.CharField(choices=[('changed', 'Alteração detectada'), ('extraction', 'Extração'), ('review', 'Revisão'), ('segment', 'Segmentação'), ('event', 'Eventos'), ('reconcile', 'Reconciliação'), ('snapshot', 'Projeção temporal'), ('invalidate', 'Invalidar cache'), ('embedding', 'Embeddings')], default='changed', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('leased', 'Em execução'), ('awaiting_review', 'Aguardando revisão'), ('completed', 'Concluída'), ('failed', 'Falha'), ('cancelled', 'Cancelada')], db_index=True, default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='norm_work_status_created_idx'), models.Index(fields=['source_kind', 'source_id', 'source_revision'], name='norm_work_source_revision_idx'), models.Index(fields=['lease_until'], name='norm_work_lease_idx')],
            },
        ),
    ]
