# Generated by Django 5.2.17 on 2026-10-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_saplsyncstate_full_sweep_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='saplsyncstate',
            name='last_cursor_url',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
