# Generated by Django 5.2.17 on 2026-10-08 04:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_saplsyncstate_last_cursor_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusCoverageScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(db_index=True, max_length=64)),
                ('record_fingerprint', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(max_length=80)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=80)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('checked_until', models.DateField(blank=True, null=True)),
                ('source_checksum', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Informe um SHA-256 hexadecimal válido.')])),
                ('corpus_revision_number', models.PositiveBigIntegerField()),
                ('corpus_revision_digest', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Informe um SHA-256 hexadecimal válido.')])),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('coverage_status', models.CharField(choices=[('unknown', 'Desconhecida'), ('partial', 'Parcial'), ('reviewed', 'Revisada no escopo')], db_index=True, default='unknown', max_length=16)),
                ('missing_intervals', models.JSONField(blank=True, null=True)),
                ('pending_review_count', models.PositiveIntegerField(blank=True, null=True)),
                ('review_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_corpus_coverage_scopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['source', 'jurisdiction', 'series', 'period_start', 'created_at', 'pk'],
                'indexes': [models.Index(fields=['corpus_revision_digest', 'scope_key', 'created_at'], name='coverage_scope_revision_idx'), models.Index(fields=['jurisdiction', 'series', 'coverage_status'], name='coverage_juris_series_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('period_start__isnull', True), ('period_end__isnull', True), ('period_start__lte', models.F('period_end')), _connector='OR'), name='coverage_scope_period_order_ck')],
            },
        ),
    ]
