# Generated by Django 5.0.9 on 2025-11-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(db_index=True, max_length=100, verbose_name='Tipo')),
                ('numero', models.CharField(max_length=50, verbose_name='Número')),
                ('ano', models.IntegerField(db_index=True, verbose_name='Ano')),
                ('ementa', models.TextField(blank=True, verbose_name='Ementa')),
                ('data_publicacao', models.DateField(blank=True, db_index=True, help_text='Data de publicação oficial da norma', null=True, verbose_name='Data de Publicação')),
                ('data_vigencia', models.DateField(blank=True, db_index=True, help_text='Data de início de vigência (pode diferir da publicação devido à vacatio legis)', null=True, verbose_name='Data de Vigência')),
                ('texto_original', models.TextField(blank=True, verbose_name='Texto Original')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('pdf_url', models.URLField(blank=True, help_text='URL original do PDF no SAPL', max_length=500, verbose_name='URL do PDF')),
                ('pdf_path', models.CharField(blank=True, help_text='Caminho local do PDF baixado (data/raw/...)', max_length=500, verbose_name='Caminho do PDF')),
                ('sapl_id', models.IntegerField(blank=True, help_text='ID primário da norma no sistema SAPL', null=True, unique=True, verbose_name='ID no SAPL')),
                ('sapl_url', models.URLField(blank=True, help_text='URL da página da norma no SAPL', max_length=500, verbose_name='URL SAPL')),
                ('sapl_metadata', models.JSONField(blank=True, default=dict, help_text='Payload JSON bruto retornado pela API SAPL', verbose_name='Metadados SAPL')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('pdf_downloaded', 'PDF Baixado'), ('ocr_processing', 'OCR em Processamento'), ('ocr_completed', 'OCR Completo'), ('nlp_processing', 'NLP em Processamento'), ('ready', 'Pronto para Consolidação'), ('failed', 'Falha no Processamento')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('needs_review', models.BooleanField(default=False, help_text='Marcado se OCR teve baixa confiança ou erro de parsing', verbose_name='Requer Revisão')),
                ('processing_error', models.TextField(blank=True, help_text='Mensagem de erro caso o processamento falhe', verbose_name='Erro de Processamento')),
            ],
            options={
                'verbose_name': 'Norma',
                'verbose_name_plural': 'Normas',
                'ordering': ['-ano', '-numero'],
                'indexes': [models.Index(fields=['tipo', 'numero', 'ano'], name='legislation_tipo_4258a4_idx'), models.Index(fields=['sapl_id'], name='legislation_sapl_id_01e3ce_idx'), models.Index(fields=['status'], name='legislation_status_19cd5d_idx'), models.Index(fields=['data_publicacao'], name='legislation_data_pu_eef15a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='norma',
            constraint=models.UniqueConstraint(fields=('tipo', 'numero', 'ano'), name='unique_norma_identifier'),
        ),
    ]
