# Generated by Django 5.0.9 on 2025-11-24 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norma',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('pdf_downloaded', 'PDF Baixado'), ('ocr_processing', 'OCR em Processamento'), ('ocr_completed', 'OCR Completo'), ('segmentation_processing', 'Segmentação em Processamento'), ('segmented', 'Texto Segmentado'), ('nlp_processing', 'NLP em Processamento'), ('ready', 'Pronto para Consolidação'), ('failed', 'Falha no Processamento')], db_index=True, default='pending', max_length=30, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('artigo', 'Artigo'), ('paragrafo', 'Parágrafo'), ('inciso', 'Inciso'), ('alinea', 'Alínea'), ('item', 'Item'), ('capitulo', 'Capítulo'), ('secao', 'Seção'), ('titulo', 'Título'), ('livro', 'Livro'), ('parte', 'Parte')], db_index=True, help_text='Tipo do dispositivo (artigo, parágrafo, etc.)', max_length=20, verbose_name='Tipo')),
                ('numero', models.CharField(help_text='Número ou identificador do dispositivo (ex: "1º", "I", "a")', max_length=50, verbose_name='Número')),
                ('texto', models.TextField(help_text='Conteúdo textual do dispositivo', verbose_name='Texto')),
                ('ordem', models.IntegerField(db_index=True, help_text='Ordem sequencial do dispositivo na norma (para preservar sequência original)', verbose_name='Ordem')),
                ('segmentation_confidence', models.FloatField(default=1.0, help_text='Confiança do regex na identificação deste dispositivo (0-1)', verbose_name='Confiança da Segmentação')),
                ('texto_bruto', models.TextField(blank=True, help_text='Texto original antes da limpeza (para auditoria)', verbose_name='Texto Bruto')),
                ('dispositivo_pai', models.ForeignKey(blank=True, help_text='Dispositivo pai na hierarquia (null para elementos raiz)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='legislation.dispositivo', verbose_name='Dispositivo Pai')),
                ('norma', models.ForeignKey(help_text='Norma à qual este dispositivo pertence', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='legislation.norma', verbose_name='Norma')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['norma', 'ordem'],
                'indexes': [models.Index(fields=['norma', 'tipo'], name='legislation_norma_i_26c17c_idx'), models.Index(fields=['norma', 'ordem'], name='legislation_norma_i_e20616_idx'), models.Index(fields=['dispositivo_pai'], name='legislation_disposi_75b1c1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.UniqueConstraint(fields=('norma', 'ordem'), name='unique_dispositivo_ordem'),
        ),
    ]
