# Generated by Django 5.0.9 on 2025-11-24 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0002_alter_norma_status_dispositivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norma',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('pdf_downloaded', 'PDF Baixado'), ('ocr_processing', 'OCR em Processamento'), ('ocr_completed', 'OCR Completo'), ('segmentation_processing', 'Segmentação em Processamento'), ('segmented', 'Texto Segmentado'), ('entity_extraction', 'Extração de Entidades'), ('entities_extracted', 'Entidades Extraídas'), ('nlp_processing', 'NLP em Processamento'), ('ready', 'Pronto para Consolidação'), ('failed', 'Falha no Processamento')], db_index=True, default='pending', max_length=30, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='EventoAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('acao', models.CharField(choices=[('REVOGA', 'Revogação'), ('ALTERA', 'Alteração'), ('ADICIONA', 'Adição'), ('SUBSTITUI', 'Substituição'), ('REGULAMENTA', 'Regulamentação'), ('REFERENCIA', 'Referência')], db_index=True, help_text='Tipo de ação legal (revoga, altera, etc.)', max_length=20, verbose_name='Ação')),
                ('target_text', models.CharField(help_text='Texto bruto da referência extraída (ex: "o Art. 5º da Lei 123/2020")', max_length=500, verbose_name='Texto da Referência')),
                ('extraction_confidence', models.FloatField(default=0.0, help_text='Confiança do NER na extração (0-1)', verbose_name='Confiança da Extração')),
                ('extraction_method', models.CharField(default='regex', help_text='Método usado para extração (regex, spacy, bert, etc.)', max_length=50, verbose_name='Método de Extração')),
                ('referencia_tipo', models.CharField(blank=True, help_text='Tipo do elemento referenciado (artigo, parágrafo, lei, etc.)', max_length=50, verbose_name='Tipo Referenciado')),
                ('referencia_numero', models.CharField(blank=True, help_text='Número do elemento referenciado (ex: "5º", "123/2020")', max_length=50, verbose_name='Número Referenciado')),
                ('validado', models.BooleanField(default=False, help_text='Se a referência foi validada/confirmada manualmente', verbose_name='Validado')),
                ('dispositivo_alvo', models.ForeignKey(blank=True, help_text='Dispositivo específico que é alvo da alteração', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_recebidas', to='legislation.dispositivo', verbose_name='Dispositivo Alvo')),
                ('dispositivo_fonte', models.ForeignKey(help_text='Dispositivo que origina a alteração', on_delete=django.db.models.deletion.CASCADE, related_name='alteracoes_causadas', to='legislation.dispositivo', verbose_name='Dispositivo Fonte')),
                ('norma_alvo', models.ForeignKey(blank=True, help_text='Norma que é alvo da alteração (se identificada)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_recebidas', to='legislation.norma', verbose_name='Norma Alvo')),
            ],
            options={
                'verbose_name': 'Evento de Alteração',
                'verbose_name_plural': 'Eventos de Alteração',
                'ordering': ['dispositivo_fonte__norma', 'dispositivo_fonte__ordem'],
                'indexes': [models.Index(fields=['dispositivo_fonte', 'acao'], name='legislation_disposi_1d69a3_idx'), models.Index(fields=['norma_alvo'], name='legislation_norma_a_414728_idx'), models.Index(fields=['dispositivo_alvo'], name='legislation_disposi_846612_idx'), models.Index(fields=['acao'], name='legislation_acao_61efb2_idx')],
            },
        ),
    ]
