# Generated by Django 5.0.9 on 2025-11-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0003_alter_norma_status_eventoalteracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='norma',
            name='texto_consolidado',
            field=models.TextField(blank=True, help_text='Texto legal consolidado após aplicação de todas as alterações', verbose_name='Texto Consolidado'),
        ),
        migrations.AlterField(
            model_name='norma',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('pdf_downloaded', 'PDF Baixado'), ('ocr_processing', 'OCR em Processamento'), ('ocr_completed', 'OCR Completo'), ('segmentation_processing', 'Segmentação em Processamento'), ('segmented', 'Texto Segmentado'), ('entity_extraction', 'Extração de Entidades'), ('entities_extracted', 'Entidades Extraídas'), ('consolidation', 'Consolidação em Processamento'), ('consolidated', 'Consolidado'), ('nlp_processing', 'NLP em Processamento'), ('ready', 'Pronto para Consolidação'), ('failed', 'Falha no Processamento')], db_index=True, default='pending', max_length=30, verbose_name='Status'),
        ),
    ]
