# Generated by Django 5.0.9 on 2025-11-24 03:42

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0005_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Vetor de embedding para busca semântica (gerado via Ollama/BERTimbau)', null=True, verbose_name='Embedding Vetorial'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='embedding_generated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp de quando o embedding foi gerado', null=True, verbose_name='Data de Geração do Embedding'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='embedding_model',
            field=models.CharField(blank=True, help_text='Nome do modelo usado para gerar o embedding (ex: "nomic-embed-text")', max_length=100, verbose_name='Modelo de Embedding'),
        ),
    ]
