# Generated by Django 5.0.9 on 2025-11-25 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0007_create_ivfflat_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(blank=True, help_text='Título da sessão (gerado a partir da primeira pergunta ou manual)', max_length=200, verbose_name='Título')),
                ('is_active', models.BooleanField(default=True, help_text='Se esta sessão está atualmente ativa', verbose_name='Ativa')),
                ('user', models.ForeignKey(help_text='Usuário dono desta sessão de conversa', on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão de Chat',
                'verbose_name_plural': 'Sessões de Chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente')], help_text='Papel da mensagem (usuário ou assistente)', max_length=10, verbose_name='Papel')),
                ('content', models.TextField(help_text='Conteúdo da mensagem (pergunta do usuário ou resposta do assistente)', verbose_name='Conteúdo')),
                ('sources_json', models.JSONField(blank=True, default=list, help_text='Lista de fontes citadas na resposta (JSON)', verbose_name='Fontes')),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Metadados da resposta (modelo usado, confidence, etc.)', verbose_name='Metadados')),
                ('session', models.ForeignKey(help_text='Sessão de chat à qual esta mensagem pertence', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='legislation.chatsession', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Mensagem de Chat',
                'verbose_name_plural': 'Mensagens de Chat',
                'ordering': ['session', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='legislation_user_id_687901_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['is_active'], name='legislation_is_acti_16ffd0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='legislation_session_cd1b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role'], name='legislation_role_2630ec_idx'),
        ),
    ]
