# Generated by Django 5.0.9 on 2026-09-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0009_chatsession_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='caminho',
            field=models.CharField(blank=True, db_index=True, help_text='Caminho materializado na hierarquia (ex: "Art. 1º > § 2º > Inciso III")', max_length=500, verbose_name='Caminho Hierárquico'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='nivel',
            field=models.IntegerField(db_index=True, default=0, help_text='Nível na árvore hierárquica (0 = raiz)', verbose_name='Nível Hierárquico'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['norma', 'nivel'], name='legislation_norma_i_44d932_idx'),
        ),
    ]
