# Generated by Django 5.2.17 on 2026-10-01 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0018_embedding_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client_session_id', models.CharField(max_length=80)),
                ('client_turn_id', models.UUIDField()),
                ('payload_digest', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('reserved', 'Reservado'), ('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado'), ('interrupted', 'Interrompido')], default='reserved', max_length=16)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='legislation.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_turns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='legislation.chatturn'),
        ),
        migrations.AddIndex(
            model_name='chatturn',
            index=models.Index(fields=['user', 'state', 'updated_at'], name='legislation_user_id_aaff02_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatturn',
            constraint=models.UniqueConstraint(fields=('user', 'client_session_id', 'client_turn_id'), name='unique_chat_turn_client_identity'),
        ),
    ]
