# Generated by Django 5.2.17 on 2026-10-01 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0019_chat_turn_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatturn',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='legislation.chatturn'),
        ),
    ]
