# Generated by Django 5.2.17 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legislation", "0020_chat_turn_retry_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="is_pinned",
            field=models.BooleanField(
                default=False,
                help_text="Se esta conversa deve permanecer no topo do histórico do usuário",
                verbose_name="Fixada",
            ),
        ),
    ]
