# Generated by Django 5.2.17 on 2026-10-03 04:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0021_chatsession_is_pinned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='norma',
            name='data_norma',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='norma',
            name='identity_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='norma',
            name='identity_key',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='DocumentoNormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document_key', models.CharField(max_length=64, unique=True)),
                ('source_kind', models.CharField(choices=[('archive', 'Acervo local'), ('sapl', 'SAPL'), ('official_gazette', 'Diário oficial'), ('legacy', 'Registro legado')], max_length=24)),
                ('source_ref', models.CharField(max_length=1000)),
                ('archive_sha256', models.CharField(blank=True, db_index=True, max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Informe um SHA-256 hexadecimal válido.')])),
                ('entry_index', models.PositiveIntegerField(blank=True, null=True)),
                ('entry_name', models.CharField(blank=True, max_length=1000)),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('role', models.CharField(choices=[('original', 'Original'), ('republicacao', 'Republicação'), ('retificacao', 'Retificação'), ('anexo', 'Anexo'), ('indeterminado', 'Indeterminado')], default='indeterminado', max_length=20)),
                ('storage_key', models.CharField(blank=True, help_text='Chave relativa do storage; nunca um caminho absoluto de disco.', max_length=500)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_sha256', models.CharField(db_index=True, max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Informe um SHA-256 hexadecimal válido.')])),
                ('official_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('condition_of_use', models.CharField(choices=[('unknown', 'Desconhecida'), ('public_record_reviewed', 'Registro público revisado'), ('permission_required', 'Permissão necessária'), ('licensed', 'Licenciada')], default='unknown', max_length=32)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('conflicts_json', models.JSONField(blank=True, default=list)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pendente'), ('extracted', 'Extraída'), ('partial', 'Parcial'), ('needs_review', 'Requer revisão'), ('failed', 'Falha')], default='pending', max_length=20)),
                ('review_status', models.CharField(choices=[('pending', 'Pendente'), ('in_review', 'Em revisão'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('norma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_normativos', to='legislation.norma')),
            ],
            options={
                'ordering': ['created_at', 'public_id'],
            },
        ),
        migrations.AddField(
            model_name='norma',
            name='documento_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='normas_como_documento_base', to='legislation.documentonormativo'),
        ),
        migrations.CreateModel(
            name='ExtracaoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('extractor_version', models.CharField(max_length=120)),
                ('policy_fingerprint', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Informe um SHA-256 hexadecimal válido.')])),
                ('text_version', models.CharField(max_length=80)),
                ('raw_text', models.TextField(blank=True)),
                ('legal_text', models.TextField(blank=True)),
                ('raw_text_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Informe um SHA-256 hexadecimal válido.')])),
                ('legal_text_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Informe um SHA-256 hexadecimal válido.')])),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('page_map_json', models.JSONField(blank=True, default=list)),
                ('metadata_candidates_json', models.JSONField(blank=True, default=dict)),
                ('quality_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('complete', 'Completa'), ('partial', 'Parcial'), ('unreadable', 'Ilegível')], default='partial', max_length=16)),
                ('extraction_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Informe um SHA-256 hexadecimal válido.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extracoes', to='legislation.documentonormativo')),
            ],
            options={
                'ordering': ['documento', 'created_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='documentonormativo',
            name='accepted_extraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_by_documents', to='legislation.extracaodocumento'),
        ),
        migrations.CreateModel(
            name='DocumentoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structural_key', models.CharField(max_length=160)),
                ('parent_key', models.CharField(blank=True, max_length=160, null=True)),
                ('tipo', models.CharField(max_length=32)),
                ('numero', models.CharField(max_length=80)),
                ('ordem', models.PositiveIntegerField()),
                ('texto', models.TextField()),
                ('start_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('end_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('page_index', models.PositiveIntegerField(blank=True, null=True)),
                ('marker', models.CharField(choices=[('none', 'Sem marca'), ('vetado', 'Vetado'), ('revogado', 'Revogado'), ('unknown', 'Desconhecido')], default='none', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos_documentais', to='legislation.extracaodocumento')),
            ],
            options={
                'ordering': ['extracao', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='RevisaoJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target_fingerprint', models.CharField(max_length=64)),
                ('decision', models.CharField(choices=[('approve', 'Aprovar'), ('reject', 'Rejeitar'), ('supersede', 'Substituir decisão')], max_length=12)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurix_legal_reviews', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisoes_juridicas', to='legislation.documentonormativo')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisoes_juridicas', to='legislation.eventoalteracao')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='extracaodocumento',
            index=models.Index(fields=['documento', 'status'], name='extr_doc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='extracaodocumento',
            index=models.Index(fields=['extraction_sha256'], name='extr_sha256_idx'),
        ),
        migrations.AddConstraint(
            model_name='extracaodocumento',
            constraint=models.UniqueConstraint(fields=('documento', 'extractor_version', 'policy_fingerprint'), name='unique_doc_extraction_policy'),
        ),
        migrations.AddIndex(
            model_name='documentonormativo',
            index=models.Index(fields=['norma', 'role'], name='doc_norma_role_idx'),
        ),
        migrations.AddIndex(
            model_name='documentonormativo',
            index=models.Index(fields=['source_kind', 'review_status'], name='doc_source_review_idx'),
        ),
        migrations.AddIndex(
            model_name='documentodispositivo',
            index=models.Index(fields=['extracao', 'ordem'], name='doc_device_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentodispositivo',
            constraint=models.UniqueConstraint(fields=('extracao', 'structural_key'), name='unique_extraction_device_key'),
        ),
        migrations.AddIndex(
            model_name='revisaojuridica',
            index=models.Index(fields=['decision', 'created_at'], name='review_action_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='revisaojuridica',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('documento__isnull', False), ('evento__isnull', True)), models.Q(('documento__isnull', True), ('evento__isnull', False)), _connector='OR'), name='legal_review_exactly_one_target'),
        ),
    ]
