# Generated by Django 5.2.17 on 2026-10-03 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0022_norma_data_norma_norma_identity_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoalteracao',
            name='effective_date_basis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='eventoalteracao',
            name='effective_date_status',
            field=models.CharField(choices=[('unknown', 'Desconhecida'), ('candidate', 'Candidata'), ('confirmed', 'Confirmada')], db_index=True, default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='eventoalteracao',
            name='effective_on',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoalteracao',
            name='evidence_json',
            field=models.JSONField(blank=True, default=dict, help_text='Citação literal e spans da extração que sustentam o evento candidato.'),
        ),
        migrations.AddField(
            model_name='eventoalteracao',
            name='review_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_revisados', to='legislation.revisaojuridica'),
        ),
        migrations.AddField(
            model_name='eventoalteracao',
            name='target_reference_json',
            field=models.JSONField(blank=True, default=dict, help_text='Candidato tipado de identidade/alvo; não constitui validação jurídica.'),
        ),
    ]
