# Generated by Django 5.2.17 on 2026-10-03 17:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0023_eventoalteracao_effective_date_basis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormativeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('complete', 'Completa'), ('partial', 'Parcial'), ('not_reconstructable', 'Não reconstruível')], max_length=24)),
                ('input_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Informe um SHA-256 hexadecimal válido.')])),
                ('content_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Informe um SHA-256 hexadecimal válido.')])),
                ('coverage_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normative_snapshots', to='legislation.norma')),
            ],
            options={
                'ordering': ['norma_id', 'as_of', 'created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structural_key', models.CharField(max_length=160)),
                ('text', models.TextField()),
                ('legal_status', models.CharField(default='in_force', max_length=24)),
                ('provenance_json', models.JSONField(blank=True, default=dict)),
                ('base_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot_uses', to='legislation.documentodispositivo')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='legislation.normativesnapshot')),
            ],
            options={
                'ordering': ['base_device__ordem', 'structural_key'],
            },
        ),
        migrations.AddIndex(
            model_name='normativesnapshot',
            index=models.Index(fields=['norma', 'as_of', 'status'], name='norm_snapshot_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='normativesnapshot',
            constraint=models.UniqueConstraint(fields=('norma', 'as_of', 'input_sha256'), name='unique_normative_snapshot_input'),
        ),
        migrations.AddConstraint(
            model_name='snapshotdispositivo',
            constraint=models.UniqueConstraint(fields=('snapshot', 'structural_key'), name='unique_snapshot_device_key'),
        ),
    ]
