# Generated by Django 5.2.17 on 2026-10-03 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0024_normativesnapshot_snapshotdispositivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['label', 'code'],
            },
        ),
        migrations.CreateModel(
            name='NormaTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('rule', 'Regra'), ('semantic', 'Semântica')], max_length=12)),
                ('status', models.CharField(choices=[('candidate', 'Candidata'), ('confirmed', 'Confirmada')], default='candidate', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='norma_topic_decisions', to=settings.AUTH_USER_MODEL)),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_links', to='legislation.norma')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='norm_links', to='legislation.topic')),
            ],
            options={
                'ordering': ['topic__label', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('norma', 'topic', 'version'), name='unique_norma_topic_version'), models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', 1)), _connector='OR'), name='norma_topic_score_0_1'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'candidate'), ('origin__in', ['rule', 'semantic'])), models.Q(('status', 'confirmed'), ('origin__in', ['manual', 'rule', 'semantic'])), _connector='OR'), name='norma_topic_candidate_origin')],
            },
        ),
    ]
